custom:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
  accessToken:
    expiration: "#{60 * 60 * 1000}"   # 1시간
  refreshToken:
    expiration: "#{60 * 60 * 24 * 7 * 1000}"   # 7일

spring:
  datasource:
    password: ${POSTGRES_PASSWORD}
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}  # 환경 변수 사용 권장
      secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ap-northeast-2  # AWS 서울 리전
      s3:
        bucket: letzgo-bucket-v1 # S3 버킷명
