spring:
  datasource:
    url: jdbc:postgresql://NEED_TO_INPUT:5432/meta_db
    username: admin
    password: ${spring.datasource.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: false      # 운영 환경에서는 보통 false로 설정
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: letzgo-redis
      port: 6379

logging:
  level:
    org.springframework.web: INFO
    team.klover: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN
